name: dashboard

windows:
  - main:
    layout: tiled
    panes:
      - docker logs -f slackbot_webhooks_1
      - docker logs -f slackbot_test_1
      - docker logs -f slackbot_api_1
      - zsh || bash
