language: bash

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  - |
    docker run \
      -v $PWD:/app \
      -w /app \
      node:11-alpine \
      yarn

  - |
    docker run \
      -v $PWD:/app \
      -w /app \
      node:11-alpine \
      yarn build

script:
  - docker-compose -f docker-compose.yaml -p slackbot up -d

  - docker ps

  # Run the tests
  - |
    docker run \
      -v $PWD:/app \
      -w /app \
      --env SLACKBOT_ID=$SLACKBOT_ID \
      --env SLACKBOT_TOKEN=$SLACKBOT_TOKEN \
      --env SLACK_USER_ID=$SLACK_USER_ID \
      --env SLACK_USER_TOKEN=$SLACK_USER_TOKEN \
      --env SLACK_PRIVATE_CHANNEL=$SLACK_PRIVATE_CHANNEL \
      --env SLACK_PUBLIC_CHANNEL=$SLACK_PUBLIC_CHANNEL \
      --env SLACK_PUBLIC_CHANNEL_FILE_ID=$SLACK_PUBLIC_CHANNEL_FILE_ID \
      --env CLOUD_COMPUTER_SLACKBOT_SERVER_HOST=http://api \
      --env CLOUD_COMPUTER_SLACKBOT_SERVER_PORT=3000 \
      --env CLOUD_COMPUTER_SLACK_SIGNING_SECRET=$CLOUD_COMPUTER_SLACK_SIGNING_SECRET \
      --name test \
      --network slackbot_slack-backend \
      node:11-alpine \
      yarn test --maxWorkers=4 --coverage

  # Upload test coverage
  - |
    docker run \
      -v $PWD:/app \
      -w /app \
      --env CODECOV_TOKEN=$CODECOV_TOKEN \
      --name test-coverage \
      --network slackbot_slack-backend \
      tomnlittle/node-jest:1.0 \
      yarn codecov
