language: bash

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/build

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  - |
    docker run \
      -v $PWD:/app \
      -w /app \
      node:11-alpine \
      yarn

script:
  - docker-compose -f docker-compose.yaml -p stemn-slackbot up -d

  - docker ps

  - |
    docker run \
      -v $PWD:/app \
      -w /app \
      --env SLACK_BOT_USER_TOKEN=$SLACK_TEST_USER_TOKEN \
      --env SLACK_PRIVATE_CHANNEL_1=$SLACK_PRIVATE_CHANNEL_1 \
      --env SLACK_PRIVATE_CHANNEL_2=$SLACK_PRIVATE_CHANNEL_2 \
      --env SLACK_PUBLIC_CHANNEL_1=$SLACK_PUBLIC_CHANNEL_1 \
      --env SLACK_PUBLIC_CHANNEL_2=$SLACK_PUBLIC_CHANNEL_2 \
      --env STEMN_SLACK_BOT_SERVER_HOST=http://api \
      --name test \
      --network stemn-slackbot_slack-backend \
      node:11-alpine \
      yarn test
