version: '3.5'

services:

  api:
    command: yarn start:watch

  build:
    command: yarn build:watch

  test:
    image: node:11-alpine
    command: yarn test:watch
    restart: always
    labels:
      namespace: slack
      tier: test
    environment:
      SLACK_BOT_USER_TOKEN: $SLACK_TEST_USER_TOKEN
      SLACK_PRIVATE_CHANNEL_1: $SLACK_PRIVATE_CHANNEL_1
      SLACK_PRIVATE_CHANNEL_2: $SLACK_PRIVATE_CHANNEL_2
      SLACK_PUBLIC_CHANNEL_1: $SLACK_PUBLIC_CHANNEL_1
      SLACK_PUBLIC_CHANNEL_2: $SLACK_PUBLIC_CHANNEL_2
      STEMN_SLACK_BOT_SERVER_HOST: http://api
    working_dir: /app
    volumes:
      - $PWD:/app
    networks:
      - slack-backend
