version: '3.5'

services:

  api:
    command: yarn start:watch

  test:
    image: tomnlittle/node-jest
    command: yarn test:watch
    restart: on-failure
    labels:
      namespace: slack
      tier: test
    environment:
      SLACK_BOT_ID: $SLACK_BOT_ID
      SLACK_USER_TOKEN: $SLACK_USER_TOKEN
      SLACK_BOT_TOKEN: $SLACK_BOT_TOKEN
      SLACK_PRIVATE_CHANNEL_1: $SLACK_PRIVATE_CHANNEL_1
      SLACK_PRIVATE_CHANNEL_2: $SLACK_PRIVATE_CHANNEL_2
      SLACK_PUBLIC_CHANNEL_1: $SLACK_PUBLIC_CHANNEL_1
      SLACK_PUBLIC_CHANNEL_2: $SLACK_PUBLIC_CHANNEL_2
      STEMN_SLACK_BOT_SERVER_HOST: http://api
    working_dir: /app
    volumes:
      - $PWD:/app
    networks:
      - slack-backend
