version: '3.5'

networks:
  slack-backend:
    driver: bridge

services:

  api:
    image: node:11-alpine
    command: yarn start
    restart: on-failure
    labels:
      namespace: slack
      tier: api
    environment:
      CLOUD_COMPUTER_SLACK_SIGNING_SECRET: $CLOUD_COMPUTER_SLACK_SIGNING_SECRET
      SLACKBOT_TOKEN: $SLACKBOT_TOKEN
      CLOUD_COMPUTER_SLACKBOT_SERVER_PORT: 3000
      CLOUD_COMPUTER_API_TOKEN: $CLOUD_COMPUTER_API_TOKEN
      CLOUD_COMPUTER_API_HOST: $CLOUD_COMPUTER_API_HOST
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - $PWD:/app
    networks:
      - slack-backend

  webhooks:
    image: webhookrelay/webhookrelayd:latest
    entrypoint: ./relayd --mode tunnel
    restart: on-failure
    labels:
      namespace: slack
      tier: webhook
    environment:
      KEY: $WEBHOOK_RELAY_KEY
      SECRET: $WEBHOOK_RELAY_SECRET
    networks:
      - slack-backend
