version: '3.5'

services:

  api:
    command: yarn start:watch

  test:
    image: tomnlittle/node-jest:1.0
    command: yarn test:watch --runInBand
    restart: on-failure
    labels:
      namespace: slack
      tier: test
    environment:
      SLACKBOT_ID: $SLACKBOT_ID
      SLACKBOT_TOKEN: $SLACKBOT_TOKEN
      SLACK_USER_ID: $SLACK_USER_ID
      SLACK_USER_TOKEN: $SLACK_USER_TOKEN
      SLACK_PRIVATE_CHANNEL: $SLACK_PRIVATE_CHANNEL
      SLACK_PUBLIC_CHANNEL: $SLACK_PUBLIC_CHANNEL
      SLACK_PUBLIC_CHANNEL_FILE_ID: $SLACK_PUBLIC_CHANNEL_FILE_ID
      CLOUD_COMPUTER_SLACKBOT_SERVER_HOST: http://api
      CLOUD_COMPUTER_SLACKBOT_SERVER_PORT: 3000
      CLOUD_COMPUTER_SLACK_SIGNING_SECRET: $CLOUD_COMPUTER_SLACK_SIGNING_SECRET
      CLOUD_COMPUTER_API_TOKEN: $CLOUD_COMPUTER_API_TOKEN
      CLOUD_COMPUTER_API_HOST: $CLOUD_COMPUTER_API_HOST
    working_dir: /app
    volumes:
      - $PWD:/app
    networks:
      - slack-backend
